### PR TITLE
update rake to be able to run tests

### PR DESCRIPTION
**Pull request by grosser**
```
rake
rake aborted!
NoMethodError: undefined method `=~' for #<Proc:0x00000001001f7e48 rake-10.5.0/lib/rake/application.rb:393 (lambda)>
bundler-2.5.10/lib/bundler/cli/exec.rb:58:in `load'
bundler-2.5.10/lib/bundler/cli/exec.rb:58:in `kernel_load'
bundler-2.5.10/lib/bundler/cli/exec.rb:23:in `run'
```

cc @Fryguy

### CODE REVIEW

**Comment by Fryguy** [comment]
This seems to be failing during setup of Ruby 2.2.  It's getting a weird error about Marshal failing when trying to install bundler.  This isn't an issue with this PR/gem, but looks more like a possible bug with ruby/setup-ruby, since they claim to still "support" Ruby 2.2?  It's hard to tell.

So, we can either try to fix that path, or just remove 2.2 and below and drop support for those since they are so old (or both). @grosser thoughts?

**Comment by grosser** [comment]
updated to have nicer CI names + dropped support for <2.7 + added support for 3.1-3.3

**Comment by Fryguy** [comment]
LGTM - I think this would warrant a major version bump (or at least a minor version bump).

**Review by Fryguy — APPROVED** [review]

**Comment by grosser** [comment]
afaik no need to bump major since nobody can install the new version on the old rubies + lots of gems do this all the time on minors, but 🤷 
... the major bump should be when https://github.com/danielsdeleo/deep_merge/pull/59 is removed

**Comment by grosser** [comment]
plz merge either way, I can't do it

**Pull request merged**
