### PR TITLE
Add overwrite_arrays option

### PR DESCRIPTION
**Pull request by Fryguy**
This is an extraction from
https://github.com/railsconfig/config/pull/103 where @dtaniwaki had
added this option, but had done it prior to the deep_merge extraction.

Paired with @carbonin <https://github.com/carbonin> on this.

### CODE REVIEW

**Comment by Fryguy** [comment]
The failures seem to be unrelated to my changes, but instead to a failure of bundler itself on Ruby 1.9.3 when trying to install gems.

**Comment by danielsdeleo** [comment]
I removed 1.8.7 and 1.9 from the travis config, so you should be good after a rebase.

**Comment by Fryguy** [comment]
Thanks @danielsdeleo I'll rebase and see if that fixes things.  (Sorry for the delay...right when I tweeted you I got slammed at work with our upcoming release)

**Comment by pkuczynski** [comment]
So the error on Travis happens only for Ruby 1.9.3 now:

```
$ bundle install --jobs=3 --retry=3
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
NoMethodError: undefined method `spec' for nil:NilClass
Installing rake 10.5.0
An error occurred while installing deep_merge (1.0.1), and Bundler cannot
continue.
Make sure that `gem install deep_merge -v '1.0.1'` succeeds before bundling.
```

Any suggestions?

**Comment by Fryguy** [comment]
@danielsdeleo This is green now so should be good for merge.  Once merged, would it be possible to release a new version of deep_merge?

**Comment by pkuczynski** [comment]
I got a message from @danielsdeleo and he will look at this in June...

**Comment by Fryguy** [comment]
Thanks @pkuczynski  😄

**Comment by danielsdeleo** [comment]
This looks good to me, @Fryguy feel free to merge now that you have the power.

**Comment by Fryguy** [comment]
Thanks @danielsdeleo .  Would it be possible to get a release of deep_merge with this (alas, I don't have *that* power :smile:)

**Pull request merged**
